services:
  iss-telem-ingester:
    container_name: iss-telem-ingester
    image: artemix-telem/iss-telem-ingester
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/artemix/src